version: 2.1
orbs:
  python: circleci/python@2

jobs:
  test-python:
    docker:
      - image: cimg/python:3.12-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Pipfile.lock" }}
            - v1-dependencies-
      - python/install-packages:
          args: --dev
          pkg-manager: pipenv
      - run:
          name: List installed packages
          command: pipenv run pip list
      - run:
          name: Run tests
          command: |
            echo "Activating virtual environment"
            source $(pipenv --venv)/bin/activate
            python manage.py test
      - save_cache:
          paths:
            - ".venv"
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'
      - run:
          name: found github actions config
          command: ':'

workflows:
  build-and-test:
    jobs:
      - test-python
    # - deploy:
    #     requires:
    #       - test-python
