version: 2.1
orbs:
  python: circleci/python@2

version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.12-node
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pipenv install --dev
      - run:
          name: Show virtualenv path
          command: |
            echo "Virtualenv path: $(pipenv --venv)"
      - run:
          name: Run Tests
          command: |
            pipenv run python manage.py test

workflows:
  build-and-test:
    jobs:
      - test-python
