version: 2.1
orbs:
  python: circleci/python@2

jobs:
  test-python:
    docker:
      - image: cimg/python:3.12-node
    steps:
      - checkout
      - run:
          name: Check Directory Contents
          command: ls -alh  # List all files in the current directory
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Pipfile.lock" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: pipenv install --dev
      - run:
          name: Show virtualenv path
          command: echo "Virtualenv path: $(pipenv --venv)"
      - run:
          name: Run tests
          command: pipenv run python manage.py test
      - save_cache:
          paths:
            - ".venv"
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}

workflows:
  build-and-test:
    jobs:
      - test-python
